# Generated by Django 4.1 on 2023-09-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact_contact_account_con_created_8bdae6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='templates/account/user/default.jpg', upload_to='user/%Y/%m/%d/'),
        ),
    ]
